package ExeptionHandling;

import javax.naming.InvalidNameException;

public class main {

	
	String name;
	int age;
	
	public String getName() {
		return name;
	}

	public void setName(String name) throws InvalideNameExeption {
		if(name.length() <3) throw new InvalideNameExeption("name invalide");
		this.name = name;
	}

	public int getAge() {
		
		return age;
	}

	public void setAge(int age) throws InvalideAgeExeption {
		if(age <0) throw new InvalideAgeExeption("invalide age");
		this.age = age;
	}

	public static void main(String[] args) {
	
		main m = new main();
		try {
			m.setName("yohannes");
			m.setAge(25);
		} catch (InvalideNameExeption e) {
			System.out.println(e.getMessage());
		}catch (InvalideAgeExeption e) {
			System.out.println(e.getMessage());
		}catch (Exception e) {
			System.out.println(e.getMessage());
		}finally {
			System.out.println("programm is terminated");
		}
		
	}
}
